name 'mongodb'
maintainer 'SourceFuse Technologies'
maintainer_email 'vijay.singh@sourcefuse.com'
license 'all_rights'
description 'Installs/Configures mongodb'
long_description 'Installs/Configures mongodb'
version '0.1.0'

depends 'yum'
depends 'yum-epel'
