name 'mongodb'
maintainer 'Company Name'
maintainer_email 'you@gmail.com'
license 'all_rights'
description 'Installs/Configures mongodb'
long_description 'Installs/Configures mongodb'
version '0.1.0'

depends 'yum'
depends 'yum-epel'
